// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLPws0JBRw5mRUFqVtbfJ0CgINJJm1mlE',
    appId: '1:795391532866:android:af93c76f5dce6e7b0d32db',
    messagingSenderId: '795391532866',
    projectId: 'database-e2a0d',
    databaseURL: 'https://database-e2a0d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'database-e2a0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8YmD1dBfa4GSuC8Q0B_kefWc95KxEfDY',
    appId: '1:795391532866:ios:75fac96453f6e4e10d32db',
    messagingSenderId: '795391532866',
    projectId: 'database-e2a0d',
    databaseURL: 'https://database-e2a0d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'database-e2a0d.appspot.com',
    iosBundleId: 'com.example.restaurantManagement',
  );
}
